sudo: required
services:
  - docker

before_install:
  - docker build -t njehyde/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true njehyde/react-test npm test

after_success:
  - docker build -t njehyde/multi-client ./client
  - docker build -t njehyde/multi-nginx ./nginx
  - docker build -t njehyde/multi-server ./server
  - docker build -t njehyde/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push njehyde/multi-client
  - docker push njehyde/multi-nginx
  - docker push njehyde/multi-server
  - docker push njehyde/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-762084187310
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY